spring:
  datasource:
    url: jdbc:h2:mem:tgtgdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    open-in-view: false
  
  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    jwt:
      secret: "your-256-bit-secret-key-here-must-be-longer-than-256-bits"
      expiration: 3600000  # 1시간

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 